### ISSUE TITLE
feat: make full copy of NVD json instead of (or in addition to) the parsed copy

### ISSUE THREAD

**Issue by terriko** [sec-data/mirror-sandbox#27]
This mirror would be more useful to the general public if we provided a full copy of the NVD JSON feeds:

https://nvd.nist.gov/vuln/data-feeds

(This could be in addition to the parsed stuff we use for cve-bin-tool, or could replace it and cve-bin-tool would do the parsing when importing from the mirror.)

For now, just copying those files directly into this repo would be sufficient.  But  as of September 2023 we'll likely have to generate them ourselves from the API2 interface as the NVD may no longer be providing them, but I think a lot of people would still like to have access to data in this format.   Recall that the idea is to make all of this available within the micro-mirror CDN, so we'll have distribution sorted.  We just need the tools to generate the files from the feed, either using CVE-bin-tool directly or spinning off a smaller tool that does that and only that.

**Comment by b31ngd3v** [comment]
updated the action to upload the json_feed (https://github.com/sec-data/mirror-sandbox/tree/main/json_feed) also, but since nvd will not provide json feed from september, should we work on a feature that will fetch the data from the api and export the data as json (same schema that nvd json has now), and a method to import them? @terriko

**Comment by terriko** [comment]
Thanks for getting the initial stuff done!

I'd say we should plan to add a feature to handle the export before September if we can.  I'd treat this as lower priority than your Github Action/GSoC work, but probably worth working on occasionally when you're waiting for code reviews or tests to run?

We should ping @anthonyharrison for feedback on best practices when we have our meeting on Wednesday too -- I know he had some insights into pain points in using NVD from folk outside of the cve-bin-tool community.

**Comment by terriko** [comment]
Just a note from our meeting today: it seems likely that the September JSON shutoff will get pushed, so while I still think it might be useful to build tooling that takes the API and spits out the same JSON format, it's probably non-urgent and may be important to wait for the next round of announcements before putting much engineering time on this.

**Comment by terriko** [comment]
official nvd news announcement:

>**Traditional Data Feeds and 1.0 API Retirement Extension**
>We have received a great deal of feedback regarding the 2.0 APIs. Due to this feedback, we will be extending the retirement date for the legacy data feeds for another 3 months.

That puts the new date for shutoff as December 15th, 2023. 

Since we've got the mirror here and in cveb.in working with full JSON I'm going to close this as done.  But I will open a new issue on the main cve-bin-tool repo for potentially writing mirror code to translate API 2.0 into the old JSON files before December.
